version: '3'
services:
  backend-server:
    restart: unless-stopped
    build:
      context: ./backend-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - llm-server
      - mysql
      - redis
    environment:
      - REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=openchat
      - DB_USERNAME=dbuser
      - DB_PASSWORD=dbpass
    volumes:
      - shared_data:/app/shared_data
    networks:
      - openchat_network

  llm-server:
    restart: unless-stopped
    build:
      context: ./llm-server
      dockerfile: Dockerfile
    volumes:
      - shared_data:/app/shared_data
    networks:
      - openchat_network

  mysql:
    restart: unless-stopped
    platform: linux/x86_64
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openchat
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      - database:/var/lib/mysql
    networks:
      - openchat_network

  redis:
    restart: unless-stopped
    image: "redis:3.2"
    ports:
      - "6379:6379"
    networks:
      - openchat_network

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - openchat_network

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - openchat_network

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.9
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - openchat_network

networks:
  openchat_network:

volumes:
  shared_data:
  database: